apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: upstream/static
    contents:
      - path: tailscale
        git:
          url: https://github.com/tailscale/tailscale
          ref: "v1.68.2"
          shallow: true
          depth: 1
        includePaths:
          - cmd/k8s-operator/deploy/manifests/operator.yaml
        newRootPath: cmd/k8s-operator/deploy/manifests/
        excludePaths:
          - LICENSE
  - path: upstream/charts
    contents:
      - path: tailscale
        helmChart:
          name: tailscale-operator
          version: "v1.68.1"
          repository:
            url: "https://pkgs.tailscale.com/helmcharts"
